## 4-е домашнее задание - Библиотека numpy

Подпишите этот блокнот: укажите ФИО и номер группы. Выполненное задание загрузите в свой репозиторий «<b>Spring2023Python</b>» в github в папку "<b>homework04</b>".  

Перед выполнением этого домашнего задания полезно прочитать про возможности и основные методы библиотеки numpy:  
http://acm.mipt.ru/twiki/bin/view/Cintro/PythonNumpy  


1.	Создайте равномерное разбиение интервала от -1.3 до 2.5 на 64 отрезка.

In [2]:
import numpy as np

np.linspace(-1.3, 2.5, 65)

array([-1.3     , -1.240625, -1.18125 , -1.121875, -1.0625  , -1.003125,
       -0.94375 , -0.884375, -0.825   , -0.765625, -0.70625 , -0.646875,
       -0.5875  , -0.528125, -0.46875 , -0.409375, -0.35    , -0.290625,
       -0.23125 , -0.171875, -0.1125  , -0.053125,  0.00625 ,  0.065625,
        0.125   ,  0.184375,  0.24375 ,  0.303125,  0.3625  ,  0.421875,
        0.48125 ,  0.540625,  0.6     ,  0.659375,  0.71875 ,  0.778125,
        0.8375  ,  0.896875,  0.95625 ,  1.015625,  1.075   ,  1.134375,
        1.19375 ,  1.253125,  1.3125  ,  1.371875,  1.43125 ,  1.490625,
        1.55    ,  1.609375,  1.66875 ,  1.728125,  1.7875  ,  1.846875,
        1.90625 ,  1.965625,  2.025   ,  2.084375,  2.14375 ,  2.203125,
        2.2625  ,  2.321875,  2.38125 ,  2.440625,  2.5     ])

2.	Сгенерируйте numpy массив длины $3n$, заполненный циклически числами 1, 2, 3, 1, 2, 3, 1....

In [3]:
n = int(input())
arr = np.array([1, 2, 3]*n)
print(arr)

4
[1 2 3 1 2 3 1 2 3 1 2 3]


3.	Создайте массив первых 10 нечетных целых чисел.

In [4]:
a = np.arange(1,20,2)
print(a)

[ 1  3  5  7  9 11 13 15 17 19]


4.  Создайте массив нулей размера 10 x 10, а затем создайте в нём "рамку" из единиц по краям.

In [5]:
a = np.zeros((10, 10))
a[0,:] = 1
a[9,:] = 1
a[:,0] = 1
a[:,9] = 1

print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


5.  Создайте массив 8 x 8 с шахматной доской из нулей и единиц.

In [6]:
a = np.zeros((8, 8))
a[::2, ::2] = 1
a[1::2, 1::2] = 1
print(a)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


6.  Создайте функцию, которая создает $n×n$ матрицу с $(i,j)$-элементом, равным $i+j$.

In [8]:
n = int(input())
arr = np.zeros((n,n))
for i in range(0, n):
    for j in range(0, n):
        arr[i][j] = i+j
print(arr)

4
[[0. 1. 2. 3.]
 [1. 2. 3. 4.]
 [2. 3. 4. 5.]
 [3. 4. 5. 6.]]


7. Примените функцию dot для перемножения вектор на вектор, матрицу на вектор и матрицу на матрицу.

In [7]:
A = [1, 2, 3, 4, 5]
B = [[6], [7], [8], [9], [10]]
C = [[10, 9, 8, 7, 6], [5, 4, 3, 2, 1]]
D = [[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]]

print(np.dot(A,B))
print(np.dot(C,B))
print(np.dot(C,D))

[130]
[[310]
 [110]]
[[180 220]
 [ 55  70]]


8. Вычислите cos(x) и sin(x) на интервале [0,1] с шагом $0.05$, а затем объедините оба массива чисел как строки в один массив.

In [9]:
c = list(np.cos(np.linspace(0, 1, 20)))
s = list(np.sin(np.linspace(0, 1, 20)))
print(c+s)

[1.0, 0.9986152781425827, 0.9944649474795756, 0.9875605021181478, 0.9779210635311101, 0.9655733276010717, 0.9505514906876966, 0.9328971549228098, 0.912659212995635, 0.8898937127472434, 0.8646637019492132, 0.8370390536963741, 0.8070962728972044, 0.7749182843977933, 0.7405942033261461, 0.7042190882928544, 0.6658936781316236, 0.625724112908743, 0.5838216399741468, 0.5403023058681398, 0.0, 0.05260728333807213, 0.10506887376594912, 0.15723948186175024, 0.20897462406278547, 0.2601310228046501, 0.3105670033203749, 0.3601428860007191, 0.40872137322898616, 0.4561679296190457, 0.5023511546035125, 0.547143146340223, 0.5904198559291864, 0.6320614309590333, 0.6719525474315213, 0.7099827291448582, 0.7460466536513234, 0.7800444439418607, 0.8118819450498316, 0.8414709848078965]


9. Создайте матрицу $A$ размера $3×5$ из случайных чисел с равномерным распределением на отрезке $[-1,3]$ (используйте np.random.rand)

In [10]:
arr = np.random.rand(3, 5)*4 - 1
print(arr)

[[ 2.71886005 -0.44364082  2.39338687  0.54714312 -0.81985907]
 [-0.95684889  2.83282016  2.73814209  1.99107112  0.84095467]
 [ 2.94255103  2.27794911  2.6533358   2.64939485 -0.86748603]]


10. Найдите сумму всех элементов, сумму внутри строк, сумму внутри столбцов, а также среднее значение, дисперсию и стандартное отклонение чисел для каждой строки матрицы $A$. (Подобно тому, как sorted имеет необязательный аргумент key=, многие функции Numpy имеют необязательный аргумент axis=)


In [11]:
print(arr.sum())
print(arr.sum(1))
print(arr.sum(0))
mean = arr.mean(1)
print(mean)
print(arr.var(1))
std = arr.std(1)
print(std)

21.49777406768827
[4.39589015 7.44613915 9.65574476]
[ 4.70456219  4.66712845  7.78486476  5.1876091  -0.84639044]
[0.87917803 1.48922783 1.93114895]
[2.08481646 2.00408466 2.00259866]
[1.44388935 1.41565697 1.41513203]


11.  Отнимите от каждого элемента матрицы $A$ среднее по строке и поделите на стандартное отклонение строки.

In [12]:
for i in range(0, len(arr)):
    arr[i,:] -= mean[i]
    arr[i,:] /= std[i]
print(arr)

[[ 1.27411565 -0.91614974  1.04870144 -0.22995869 -1.17670866]
 [-1.72787389  0.94909456  0.88221531  0.35449498 -0.45793097]
 [ 0.7147051   0.24506559  0.51033178  0.50754692 -1.97764938]]


12. Отсортируйте матрицу $A$ по 3-ому столбцу, т.е. поменяйте местами строки матрицы так, чтобы 3-й столбец оказался отсортированным. Используйте для этого slicing + argsort + indexing.

In [13]:
print(arr[arr[:, 2].argsort()])

[[ 0.7147051   0.24506559  0.51033178  0.50754692 -1.97764938]
 [-1.72787389  0.94909456  0.88221531  0.35449498 -0.45793097]
 [ 1.27411565 -0.91614974  1.04870144 -0.22995869 -1.17670866]]


13. Посчитайте две матрицы: $B = A^TA$ и $C = AA^T$. Что вы можете о них сказать? Какого они размера? В чём их сходство и отличие?

In [14]:
B = np.dot(np.transpose(arr), arr)
C = np.dot(arr, np.transpose(arr))
print(B)
print(C)

[[ 5.11972225e+00 -2.63204681e+00  1.76546831e-01 -5.42770221e-01
  -2.12145205e+00]
 [-2.63204681e+00  1.80016797e+00  1.60296544e-03  6.71508138e-01
   1.58767733e-01]
 [ 1.76546831e-01  1.60296544e-03  2.13851709e+00  3.30600214e-01
  -2.64726710e+00]
 [-5.42770221e-01  6.71508138e-01  3.30600214e-01  4.36151567e-01
  -8.95489698e-01]
 [-2.12145205e+00  1.58767733e-01 -2.64726710e+00 -8.95489698e-01
   5.50544112e+00]]
[[ 5.         -1.6885113   3.43168817]
 [-1.6885113   5.          0.53344237]
 [ 3.43168817  0.53344237  5.        ]]


14. Найдите сумму диагональных элементов матриц $B$ и $C$.

In [17]:
np.sum(np.diagonal(B)) + np.sum(np.diagonal(C))

29.999999999999996

15.	Посчитайте детерминант и ранг матриц $A$, $B$ и $C$, посмотрите на спектр (набор собственных значений) матриц $B$ и $C$, какие выводы вы можете сделать?  
(подсказка: используйте готовые функции из библиотеки np.linalg). 


In [20]:
print(np.linalg.det(B))
print(np.linalg.det(C))
print(np.linalg.matrix_rank(arr))
print(np.linalg.matrix_rank(B))
print(np.linalg.matrix_rank(C))
w_B, v_B = np.linalg.eig(B)
w_C, v_C = np.linalg.eig(C)
print(w_B)
print(w_C)

import numpy as np
np.random.seed(1032201723)
np.random.randint(0, 8,size=1)


1.0476909808134983e-30
44.2574212545233
3
3
3
[8.63473551e+00 5.41951361e+00 9.45750882e-01 4.57542640e-17
 3.53953733e-16]
[0.94575088 8.63473551 5.41951361]


array([2])

16. Численно посчитать определённый интеграл  3-мя методами:  
a)	Прямоугольников $\int\limits_a^b {f(x)dx \approx \Delta x\sum\limits_{k = 0}^N {f({x_k})} }$  
b)	Трапеций $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{2}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N - 1} {f({x_k})}  + f({x_N})} \right)}$  
c)	По правилу Симпсона  $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{3}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N/2 - 1} {f({x_{2k}})}  + 4\sum\limits_{k = 1}^{N/2} {f({x_{2k - 1}})}  + f({x_N})} \right)}$  


В реализации этих методов цикл for для суммирования использовать нельзя.  
Нужно посчитать значение интеграла с некоторым шагом интегрирования (например начать с 0.1), потом уменьшить его в десять раз и ещё раз посчитать и так до тех пор пока отличие в ответах будет в 5-м знаке после запятой, т.е. чтобы ошибка была меньше 1e-5. Получить ответы для 3-х разных методов и сделать соответствующие выводы.  

Далее необходимо сравнить полученные оценки с аналитическим решением (т.е. формульным, которое вы должны сами посчитать на листочке и вбить формулу-ответ).   

В качестве интеграла взять два из следующих примеров:  
- один с номером, сгенерированным случайным образом с помощью функции np.random.randint(9), в качестве seed для генератора случайных чисел взять номер своего студенческого билета. 
- второй номер - под номером 9, несобственный интерграл. Подумайте, как сделать подбор шага интегрирования адаптивным.

<table width="80%"
       align="center">
    <tr>
        <td> 0) $\int\limits_3^4 {\frac{{{x^2} + 3}}{{x - 2}}dx}$ </td>
        <td> 1) $\int\limits_{ - 2}^{ - 1} {\frac{{x + 1}}{{{x^3} - {x^2}}}dx}$ </td>
        <td> 2) $\int\limits_1^2 {\frac{{{e^{1/{x^2}}}}}{{{x^3}}}dx}$ </td>
        <td> 3) $\int\limits_1^e {\frac{{\cos (\ln x)}}{x}dx}$ </td>
        <td> 4) $\int\limits_1^e {\frac{{dx}}{{x(1 + {{\ln }^2}x)}}}$ </td>
    </tr>                
    <tr>
        <td> 5) $\int\limits_0^{\pi /2} {{{\cos }^3}\alpha \;d\alpha }$ </td>
        <td> 6) $\int\limits_0^{1/3} {c{h^2}3x\;dx}$ </td>
        <td> 7) $\int\limits_2^3 {\frac{{dy}}{{{y^2} - 2y - 8}}dy}$ </td>
        <td> 8) $\int\limits_0^2 {\frac{{2x - 1}}{{2x + 1}}dx}$ </td>
        <td> 9) $\int\limits_{3/4}^2 {\frac{{dx}}{{\sqrt {2 + 3x - 2{x^2}} }}}$ </td>
        </tr>
</table>

In [24]:
print('Аналитическое решение интеграла 4: ', np.arctan(np.log(np.e)) - np.arctan(np.log(1)))
print('Аналитическое решение интеграла 9: ', np.pi/(2**(3/2)))

Аналитическое решение интеграла 4:  0.7853981633974483
Аналитическое решение интеграла 9:  1.1107207345395915


In [25]:
import math
h2 = 0.00001
h9 = 0.0000001
m = int((2 - 3 / 4) / h9)
xx = np.arange(1, 2, h2)
x = np.append(xx, 2)
y = np.linspace(3 / 4, 2, m, endpoint=False)

def func2(x):
    return (math.e ** (1 / x ** 2) / x ** 3)

def func9(x):
    return 1 / np.sqrt(2 + 3 * x - 2 * x ** 2, where = x!=2)

rect2 = h2 * np.sum(func2(x))
trape2 = h2 / 2 * (func2(x[0]) + 2 * np.sum(func2(x[1:-1])) + func2(x[-1]))
simp2 = h2 / 3 * (func2(x[0]) + 2 * np.sum(func2(x[2:-1:2])) + 4 * np.sum(func2(x[1:-2:2])) + func2(x[-1]))

rect9 = h9 * np.sum(func9(y))
trape9 = h9 / 2 * (func9(y[0]) + 2 * np.sum(func9(y[1:-1])) + func9(y[-1]))
simp9 = h9 / 3 * (func9(y[0]) + 2 * np.sum(func9(y[2:-1:2])) + 4 * np.sum(func9(y[1:-2:2])) + func9(y[-1]))

print('Метод прямоугольников №2 =', rect2, '\nМетод трапеций №2 =', trape2, '\nПравило Симпсона №2 =', simp2)
print('\nМетод прямоугольников №9 =', rect9, '\nМетод трапеций №9 =', trape9, '\nПравило Симпсона №9 =', simp9)
print('\nВывод: С помощью численных методов можно посчитать интеграл с заданной точностью.')
print('       Чем меньше шаг интегрирования, тем точнее решение.')

Метод прямоугольников №2 = 0.7171425999179543 
Метод трапеций №2 = 0.7171282059929266 
Правило Симпсона №2 = 0.7171260658021932

Метод прямоугольников №9 = 1.1105142375079518 
Метод трапеций №9 = 1.1104434985441538 
Правило Симпсона №9 = 1.1104013030605193

Вывод: С помощью численных методов можно посчитать интеграл с заданной точностью.
       Чем меньше шаг интегрирования, тем точнее решение.
